version: "3.3"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  

  api:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations dashboard &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"